# Root directory where all generated files and artifacts will be stored.
## we need to mention here what are the inputs data that needed for data injection 
artifacts_root: artifacts              

# Data ingestion configuration settings.
data_ingestion:                        
  root_dir: artifacts/data_ingestion   # ## once data injection file executes, it will create a root directory with this path Specifies the root directory for data ingestion artifacts.
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip 
                                        # URL to download the source data, which is a zip file.
  local_data_file: artifacts/data_ingestion/data.zip 
                                        # Path where the downloaded zip file will be stored locally.
  unzip_dir: artifacts/data_ingestion   # Directory where the data will be unzipped for further processing.

# data validation - we are going to chcek whether scema of the dataset like feature names indeendent & dependent variables are correct Data validation configuration settings.
data_validation:                        
  root_dir: artifacts/data_validation  # Root directory for data validation artifacts.
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv 
                                        #we wil chcek schema of inputs Specifies path to the unzipped data file (CSV format) for validation.
  STATUS_FILE: artifacts/data_validation/status.txt 
                                        # File to log the validation status, such as success or errors.

# Data transformation configuration settings.
data_transformation:                    
  root_dir: artifacts/data_transformation 
                                        # Root directory for data transformation artifacts.
  data_path: artifacts/data_ingestion/winequality-red.csv 
                                        # Specifies the path to the raw data file that will be transformed.

# Model trainer configuration settings.
model_trainer:                          
  root_dir: artifacts/model_trainer    # Root directory for model training artifacts.
  train_data_path: artifacts/data_transformation/train.csv 
                                        # Path to the training data file after transformation.
  test_data_path: artifacts/data_transformation/test.csv 
                                        # Path to the testing data file after transformation.
  model_name: model.joblib              # Name of the file where the trained model will be saved.

# Model evaluation configuration settings.
model_evaluation:                       
  root_dir: artifacts/model_evaluation # Root directory for model evaluation artifacts.
  test_data_path: artifacts/data_transformation/test.csv 
                                        # Specifies the path to the testing data file for evaluation.
  model_path: artifacts/model_trainer/model.joblib 
                                        # Path to the trained model that will be evaluated.
  metric_file_name: artifacts/model_evaluation/metrics.json 
                                        # File where evaluation metrics (such as accuracy or loss) will be saved in JSON format.
